### ISSUE TITLE
Pre-trained model 404 Not Found

### ISSUE THREAD

**Issue by sudhanshunathmishra** [ameroyer/PIC#1]
Hi,

I am seeing a 404 not found error for both of the following links:
1) http://pub.ist.ac.at/~aroyer/Models/PIC/cifar-model.tar.gz
2) http://pub.ist.ac.at/~aroyer/Models/PIC/imagenet-model.tar.gz 

Could you please update the links?

**Comment by ameroyer** [comment]
Hi, thanks for letting me know, there is indeed a typo in the links, it should be underscores instead of dashes (cifar_model).
You can access the models here: [http://pub.ist.ac.at/~aroyer/Models/PIC/](http://pub.ist.ac.at/~aroyer/Models/PIC/)

**Comment by jiaozizhao** [comment]
Hi, could you tell me which version of CUDA , cuDNN, python and tensorflow do you use? I always met some problems when I run the demo.
